package com.swift.browser.permissionengine

enum class CapabilityState {
    SUPPORTED,
    SUPPORTED_WITH_PERMISSION,
    SUPPORTED_WITH_POLICY,
    PARTIAL,
    REQUIRES_NATIVE_BRIDGE,
    UNSUPPORTED_BY_WEBVIEW,
    UNSUPPORTED_BY_ANDROID,
    BLOCKED_BY_SECURITY,
    BLOCKED_BY_USER_POLICY,
    DENIED_BY_ANDROID_PERMISSION,
    DENIED_BY_HARDWARE,
    CANCELED,
    FAILED
}

enum class CapabilitySupportStatus {
    SUPPORTED,
    SUPPORTED_WITH_PERMISSION,
    SUPPORTED_WITH_POLICY,
    PARTIAL,
    REQUIRES_NATIVE_BRIDGE,
    UNSUPPORTED_BY_WEBVIEW,
    UNSUPPORTED_BY_ANDROID,
    BLOCKED_BY_SECURITY,
    BLOCKED_BY_USER_POLICY,
    UNSUPPORTED
}
