package com.swift.browser.permissionengine

data class PermissionTraceModel(
    val traceId: String,
    val requestId: String,
    val origin: String,
    val topLevelOrigin: String = origin,
    val frameOrigin: String? = null,
    val capability: String = "UNKNOWN",
    val permissionType: String = capability,
    val resources: List<String> = emptyList(),
    val webApi: String = "",
    val requestSource: String = "website",
    val userGesture: Boolean? = null,
    val secureContext: Boolean = origin.startsWith("https"),
    val storedDecision: String = "UNKNOWN",
    val policyDecision: String = "ALLOW",
    val androidPermissions: List<String> = emptyList(),
    val androidResult: String = "NOT_REQUESTED",
    val hardwareResult: String = "NOT_CHECKED",
    val webViewCapability: Boolean = true,
    val finalDecision: String = "PENDING",
    val finalResources: List<String> = emptyList(),
    val timestamp: Long = System.currentTimeMillis(),
    val failureReason: String = "",
    val stage: String = "REQUEST_RECEIVED",
    val status: String = "SUCCESS",
    val reason: String = failureReason.ifBlank { "Processing" },
    val suggestedFix: String = "",
    val fileName: String = "PermissionEngine.kt",
    val className: String = "PermissionEngine",
    val methodName: String = "process",
    val callbackName: String = "N/A",
    val androidPermissionState: String = androidResult,
    val hardwareState: String = hardwareResult,
    val finalResult: String = finalDecision
)
