package com.swift.browser.extensionengine

object MessagingError {
    const val EXTENSION_NOT_FOUND = "EXTENSION_NOT_FOUND"
    const val EXTENSION_DISABLED = "EXTENSION_DISABLED"
    const val PERMISSION_DENIED = "PERMISSION_DENIED"
    const val HOST_PERMISSION_DENIED = "HOST_PERMISSION_DENIED"
    const val EXTERNAL_CONNECTION_DENIED = "EXTERNAL_CONNECTION_DENIED"
    const val MESSAGE_TIMEOUT = "MESSAGE_TIMEOUT"
    const val MESSAGE_TARGET_UNAVAILABLE = "MESSAGE_TARGET_UNAVAILABLE"
    const val MESSAGE_CONTEXT_INVALID = "MESSAGE_CONTEXT_INVALID"
    const val MESSAGE_RUNTIME_STALE = "MESSAGE_RUNTIME_STALE"
    const val PORT_NOT_FOUND = "PORT_NOT_FOUND"
    const val PORT_DISCONNECTED = "PORT_DISCONNECTED"
    const val PORT_UNAUTHORIZED = "PORT_UNAUTHORIZED"
    const val PORT_TARGET_UNAVAILABLE = "PORT_TARGET_UNAVAILABLE"
    const val PRIVATE_CONTEXT_INVALID = "PRIVATE_CONTEXT_INVALID"
    const val UNSUPPORTED_MESSAGING = "UNSUPPORTED_MESSAGING"
    const val SERIALIZATION_ERROR = "SERIALIZATION_ERROR"
    const val MESSAGE_BACKPRESSURE = "MESSAGE_BACKPRESSURE"
    const val PORT_BACKPRESSURE = "PORT_BACKPRESSURE"
}
